# 現金付款機 middleware 模組
# ebus.pl 必須最先啟動，其他模組透過 /var/lib/ebus.sock 連線

[program:ebus.pl]
command=/usr/share/perl5/ebus.pl
priority=1
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:biz.pl]
command=/opt/app/scripts/biz.pl
priority=10
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sys.pl]
command=/opt/app/scripts/sys.pl
priority=10
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sess.pl]
command=/opt/app/scripts/sess.pl
priority=10
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:order.pl]
command=/opt/app/scripts/order.pl
priority=10
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:payment.pl]
command=/opt/app/scripts/payment.pl
priority=10
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:payment_cash_standalone.pl]
command=/opt/app/scripts/payment_cash_standalone.pl
priority=10
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:invoice.pl]
command=/opt/app/scripts/invoice.pl
priority=10
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:biz_no_gui.pl]
command=/opt/app/scripts/biz_no_gui.pl
priority=20
autostart=true
autorestart=false
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
