# 現金付款機 middleware 模組
# 不使用 start.pl（固定 mods list，不讀 config.pm）

[program:sys.pl]
command=/opt/app/scripts/sys.pl
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:sess.pl]
command=/opt/app/scripts/sess.pl
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:order.pl]
command=/opt/app/scripts/order.pl
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:payment.pl]
command=/opt/app/scripts/payment.pl
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:payment_cash_standalone.pl]
command=/opt/app/scripts/payment_cash_standalone.pl
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:invoice.pl]
command=/opt/app/scripts/invoice.pl
autostart=true
autorestart=true
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0

[program:biz_no_gui.pl]
command=/opt/app/scripts/biz_no_gui.pl
autostart=true
autorestart=false
stderr_logfile=/dev/stderr
stderr_logfile_maxbytes=0
