#!/usr/bin/env bash
set -euo pipefail

cd "$(dirname "$0")/.."

usage() {
  echo "Usage: $0 <system>" >&2
  echo "Example: $0 mwd-pickup" >&2
}

if [[ $# -lt 1 ]]; then
  usage
  exit 1
fi

system="$1"
sysdir="systems/${system}"
listfile="${sysdir}/instances.txt"
sysenv="${sysdir}/system.env"

if [[ ! -f "$listfile" ]]; then
  echo "Missing: $listfile" >&2
  exit 2
fi
if [[ ! -f "$sysenv" ]]; then
  echo "Missing: $sysenv" >&2
  exit 2
fi

# Ensure mesh network exists if configured as external
# shellcheck disable=SC1090
source "$sysenv" || true
if [[ "${MESHNET_EXTERNAL:-false}" == "true" ]]; then
  if ! docker network inspect "${MESHNET_NAME:-demo-mesh}" >/dev/null 2>&1; then
    echo "==> Creating mesh network: ${MESHNET_NAME:-demo-mesh}"
    docker network create "${MESHNET_NAME:-demo-mesh}" >/dev/null
  fi
fi

mkdir -p .tmp/system-env

# shellcheck disable=SC1090
source "$sysenv" || true

write_config5() {
  local instance="$1"
  local cfg="instances/${instance}/mw/config.5"
  mkdir -p "$(dirname "$cfg")"

  # If keys are not provided, keep config.5 as a no-op (compatible with solo runs)
  if [[ -z "${MASTER_EBUS:-}" && -z "${MASTER_IP:-}" && -z "${RETRIEVER_EBUS:-}" && -z "${RETRIEVER_IP:-}" ]]; then
    return 0
  fi

  cat >"$cfg" <<EOF
# Auto-generated by scripts/system_up.sh (${system})
# Mounted into MW container as /root/config.5

MASTER_EBUS=${MASTER_EBUS:-}
MASTER_IP=${MASTER_IP:-}
RETRIEVER_EBUS=${RETRIEVER_EBUS:-}
RETRIEVER_IP=${RETRIEVER_IP:-}
EOF
}

while IFS= read -r instance; do
  [[ -z "$instance" ]] && continue
  [[ "$instance" =~ ^# ]] && continue

  instenv="instances/${instance}/.env"
  if [[ ! -f "$instenv" ]]; then
    echo "Missing env file: $instenv" >&2
    exit 3
  fi

  merged=".tmp/system-env/${system}.${instance}.env"
  # Merge env (system overrides instance on duplicate keys)
  {
    cat "$instenv"
    echo
    cat "$sysenv"
  } >"$merged"

  # Generate MW overlay config for this system
  write_config5 "$instance"

  echo "==> Starting system ${system}: ${instance}"
  docker compose -f compose.yml --env-file "$merged" up -d

done <"$listfile"
