#!/usr/bin/env python3
"""Render nginx map config from instances/apps.json.

Source of truth:
  ../instances/apps.json

Output:
  ./nginx/conf.d/apps.map.conf

Run:
  ./scripts/render_maps.py
  docker compose restart frontend
"""

import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
INSTANCES_JSON = BASE.parent / 'instances' / 'apps.json'
OUT = BASE / 'nginx' / 'conf.d' / 'apps.map.conf'


def main():
    apps = json.loads(INSTANCES_JSON.read_text(encoding='utf-8'))

    default_rest = 12001
    default_mqws = 12004

    lines = []
    lines.append('# Auto-generated from instances/apps.json')
    lines.append('# DO NOT EDIT THIS FILE BY HAND; edit instances/apps.json then run frontend/scripts/render_maps.py')
    lines.append('')

    lines.append('map $app $mq_ws_port {')
    lines.append(f'  default {default_mqws};')
    for name in sorted(apps.keys()):
        mqws = int(apps[name]['mqtt_ws_port'])
        lines.append(f'  {name} {mqws};')
    lines.append('}')
    lines.append('')

    lines.append('map $app $rest_port {')
    lines.append(f'  default {default_rest};')
    for name in sorted(apps.keys()):
        rest = int(apps[name]['rest_port'])
        lines.append(f'  {name} {rest};')
    lines.append('}')
    lines.append('')

    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {OUT}')


if __name__ == '__main__':
    main()
