#!/usr/bin/env python3
import json
from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
APPS_JSON = BASE / 'apps.json'
OUT = BASE / 'nginx' / 'conf.d' / 'apps.map.conf'

def main():
    apps = json.loads(APPS_JSON.read_text(encoding='utf-8'))

    # defaults: first app in list or sensible fallback
    default_rest = 12001
    default_mqws = 12004

    lines = []
    lines.append('# Auto-generated from frontend/apps.json')
    lines.append('# DO NOT EDIT THIS FILE BY HAND; edit apps.json then run scripts/render_maps.py')
    lines.append('')

    lines.append('map $app $mq_ws_port {')
    lines.append(f'  default {default_mqws};')
    for name in sorted(apps.keys()):
        mqws = int(apps[name]['mq_ws_port'])
        lines.append(f'  {name} {mqws};')
    lines.append('}')
    lines.append('')

    lines.append('map $app $rest_port {')
    lines.append(f'  default {default_rest};')
    for name in sorted(apps.keys()):
        rest = int(apps[name]['rest_port'])
        lines.append(f'  {name} {rest};')
    lines.append('}')
    lines.append('')

    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {OUT}')

if __name__ == '__main__':
    main()
