#!/usr/bin/env python3
"""Render nginx map config from instances/*/.env files.

Source of truth:
  ../instances/<name>/.env

Output:
  ./nginx/conf.d/apps.map.conf

Run:
  ./scripts/render_maps.py
  docker compose restart frontend
"""

from pathlib import Path

BASE = Path(__file__).resolve().parents[1]
INSTANCES_DIR = BASE.parent / 'instances'
OUT = BASE / 'nginx' / 'conf.d' / 'apps.map.conf'

ENV_KEYS = {'DEMO_NAME', 'REST_PORT', 'MQTT_WS_PORT'}


def parse_env(path: Path) -> dict:
    out = {}
    for raw in path.read_text(encoding='utf-8').splitlines():
        line = raw.strip()
        if not line or line.startswith('#'):
            continue
        if '=' not in line:
            continue
        k, v = line.split('=', 1)
        k = k.strip()
        v = v.strip()
        if k in ENV_KEYS:
            out[k] = v
    if 'DEMO_NAME' not in out:
        out['DEMO_NAME'] = path.parent.name
    return out


def list_instances() -> dict:
    """Return dict: instance_name -> {rest_port, mqtt_ws_port}"""
    apps = {}
    for d in sorted(INSTANCES_DIR.iterdir(), key=lambda p: p.name):
        if not d.is_dir():
            continue
        envf = d / '.env'
        if not envf.exists():
            continue
        cfg = parse_env(envf)
        name = cfg.get('DEMO_NAME', d.name)
        rest = cfg.get('REST_PORT')
        mqws = cfg.get('MQTT_WS_PORT')
        if rest and mqws:
            apps[name] = {'rest_port': int(rest), 'mqtt_ws_port': int(mqws)}
    return apps


def main():
    apps = list_instances()

    default_rest = 12001
    default_mqws = 12004

    lines = []
    lines.append('# Auto-generated from instances/*/.env')
    lines.append('# DO NOT EDIT THIS FILE BY HAND; run frontend/scripts/render_maps.py')
    lines.append('')

    lines.append('map $app $mq_ws_port {')
    lines.append(f'  default {default_mqws};')
    for name in sorted(apps.keys()):
        mqws = apps[name]['mqtt_ws_port']
        lines.append(f'  {name} {mqws};')
    lines.append('}')
    lines.append('')

    lines.append('map $app $rest_port {')
    lines.append(f'  default {default_rest};')
    for name in sorted(apps.keys()):
        rest = apps[name]['rest_port']
        lines.append(f'  {name} {rest};')
    lines.append('}')
    lines.append('')

    # Map Referer header to REST port for /media/ proxy
    # This allows proxying without meshnet DNS
    lines.append('# Map Referer to REST port for /media/ proxy (no meshnet needed)')
    lines.append('map $http_referer $media_proxy_port {')
    lines.append('  default "";')
    for name in sorted(apps.keys()):
        rest = apps[name]['rest_port']
        lines.append(f'  "~*/demo/{name}/" {rest};')
    lines.append('}')
    lines.append('')

    OUT.write_text('\n'.join(lines), encoding='utf-8')
    print(f'Wrote {OUT}')


if __name__ == '__main__':
    main()
